# Generated by Django 4.0.4 on 2022-05-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tag',
            table=None,
        ),
    ]
