# Generated by Django 4.0.4 on 2022-05-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_is_published_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_published',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('P', 'Published'), ('PP', 'Pinned'), ('UP', 'Unpublished')], default='UP', max_length=2, verbose_name='post status'),
        ),
    ]
