# Generated by Django 4.0.4 on 2022-05-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_is_published_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('P', 'Published'), ('PP', 'Pinned'), ('UP', 'Unpublished')], default='UP', max_length=2, verbose_name='status'),
        ),
    ]
